      SUBROUTINE ADAJ(NC,JDT,M,IDA,NYD)
!     APEX0806
!     THIS SUBPROGRAM COMPUTES THE DAY OF THE YEAR, GIVEN THE MONTH AND
!     THE DAY OF THE MONTH.
      DIMENSION NC(13)
      JDT=NC(M)+IDA
      IF(M>2)JDT=JDT-NYD
      RETURN
      END