      FUNCTION ADSTN(RN1,RN2)
!     APEX0806
!     THIS SUBPROGRAM COMPUTES A STANDARD NORMAL DEVIATE GIVEN TWO RANDO
!     NUMBERS
      ADSTN=SQRT(-2.*LOG(RN1))*COS(6.283185*RN2)
      RETURN
      END