      SUBROUTINE AISPL(II,JJ)
!     APEX0806
!     THIS SUBPROGRAM SPLITS DUAL PURPOSE INTEGER INPUT VARIABLES.
      USE PARM
      XX=II
      XX=XX*.1
      JJ=XX
      II=II-JJ*10
      RETURN
      END