      SUBROUTINE APAGE(IP)
!     APEX0806
!     THIS SUBPROGRAM CHANGES PAGES, WRITES VERSION, DATE, & TITLE
      USE PARM
      WRITE(KW(1),1)IYER,IMON,IDAY,IT1,IT2,IT3
      WRITE(KW(1),5)IRUN
      WRITE(KW(1),2)TITLE
      IF(IP==0)RETURN
      WRITE(KW(1),4)SITEFILE
      WRITE(KW(1),4)SAFILE
      IF(NGN>0)WRITE(KW(1),4)FWTH(IRF(ISA))
      WRITE(KW(1),4)TITSO(ISA)
      WRITE(KW(1),4)TITOP(ISA)
	  IF(IPTS(ISA)>0)WRITE(KW(1),4)FPSO(IPTS(ISA))
      WRITE(KW(1),3)ISA,NBSA(ISA),TITSA(ISA)
      RETURN
    1 FORMAT('1'/T5,'APEX0806',2X,3I4,2X,2(I2,':'),I2)
    2 FORMAT(10X,20A4)
    3 FORMAT(10X,'SA#= ',I8,1X,'ID= ',I8,A80)
    4 FORMAT(10X,A20)
    5 FORMAT(10X,'RUN # ',I4)
      END