      FUNCTION ARALT(X,DRV)
!     APEX0806
!     THIS SUBPROGRAM INTERPOLATES MONTHLY VALUES OF DAYLIGHT HOURS AND
!     MAXIMUM SOLAR RADIATION TO PROVIDE DAILY VALUES.
      USE PARM
      DIMENSION X(12)
      M1=MO+1
      N2=NC(M1)
      IF(MO==2)N2=N2-NYD
      N1=NC(MO)
      X1=JDA-N1
      X2=N2-N1
      RTO=X1/X2
      IF(M1==13)M1=1
      XX=X(M1)-X(MO)
      DRV=XX/X2
      ARALT=XX*RTO+X(MO)
      RETURN
      END