      SUBROUTINE CFRG(I,J,F,STRX,X,JRT)
!     APEX0806
!     THIS SUBPROGRAM DETERMINES MINIMUM STRESS FACTORS FOR ROOT AND
!     TOTAL BIOMASS GROWTH.
      JRT=0
      IF(F<STRX)THEN
          STRX=MAX(0.,F)
          J=I
          IF(STRX<=X)JRT=1
      END IF
      RETURN
      END