      SUBROUTINE HLGB(Q,EV,O,RG,VLGE,VLGB,WW,ISA,KW,NBSA,MSO)
!     APEX0806
!     THIS SUBPROGRAM CHECKS THE LAGOON WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION NBSA(ISA),KW(MSO)
      DF=VLGB+Q-EV-O-VLGE-RG+WW
	  PER=200.*DF/(VLGB+VLGE)
!	  IF(ABS(PER)<1.)RETURN
	  WRITE(KW(1),2)ISA,NBSA(ISA)
	  WRITE(KW(1),3)PER,DF,VLGB,Q,EV,O,RG,WW,VLGE
      VLGB=VLGE
      RETURN
    2 FORMAT(/T10,'LAGOON WATER BALANCE',2X,'SA#= ',I8,1X,'ID= ',I8)
    3 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'VLGB=',E13.6,2X,&
     &'QI  =',E13.6,2X,'ET  =',E13.6/5X,'QO  =',E13.6,2X,'IRG =',E13.6,&
     &2X,'WW  =',E13.6,2X,'VLGF=',E13.6)
      END