      FUNCTION HQP(X1,CQRB,ITP,INT)
      DIMENSION CQRB(8,17,4)
!     APEX0806
!     THIS SUBPROGRAM SOLVES THE 7TH DEGREE POLYNOMIAL RELATING TR55
!     PEAK RATE FACTOR TO TIME OF CONCENTRATION.
      HQP=CQRB(1,INT,ITP)+X1*(CQRB(2,INT,ITP)+X1*(CQRB(3,INT,ITP)+X1*&
     &(CQRB(4,INT,ITP)+X1*(CQRB(5,INT,ITP)+X1*(CQRB(6,INT,ITP)+X1*(CQRB(&
     &7,INT,ITP)+X1*CQRB(8,INT,ITP)))))))
      RETURN
      END