      SUBROUTINE HRFEI
!     APEX0806
!     THIS SUBPROGRAM ESTIMATES THE USLE RAINFALL ENERGY FACTOR, GIVEN
!     DAILY RAINFALL.
      USE PARM
      DATA ALMN/.02083/
      IF(ITYP==0)THEN
          AJP=1.-EXP(-125./(RFV(IRF(ISA))+5.))
          AL5=ATRI(ALMN,WI(IWI,MO),AJP,4)
      ELSE
          AL5=WI(IWI,MO)
      END IF
      PRFF=-2.*LOG(1.-AL5)
      RFI5=2.*RFV(IRF(ISA))*AL5+.001
      IF(REP<1.E-5)REP=PRFF*RFV(IRF(ISA))+.001
      DUR=MIN(24.,4.605/PRFF)
      EI=MAX(0.,RFV(IRF(ISA))*(12.1+8.9*(LOG10(REP)-.4343))*RFI5/1000.)
      RETURN
      END