      SUBROUTINE HRUNF
!     APEX0806
!     THIS SUBPROGRAM DISTRIBUTES DAILY RAINFALL UNIFORMLY &
!     FURNISHES THE GREEN & AMPT SUBPROGRAM RAIN INCREMENTS OF EQUAL
!     VOLUME = DRFV
      USE PARM
      DATA DRFV/5./
      PT=0.
      DO WHILE(PT<RFV(IRF(ISA)))
          PT=PT+DRFV
          CALL HGASP(DRFV,PT,Q1,REP)
      END DO
      A=RFV(IRF(ISA))-PT+DRFV
      PT=RFV(IRF(ISA))
      CALL HGASP(A,PT,Q1,REP)
      RETURN
      END