      SUBROUTINE HSNOM
!     APEX0806
!     THIS SUBPROGRAM PREDICTS DAILY SNOW MELT WHEN THE AVERAGE AIR
!     TEMPERATURE EXCEEDS 0 DEGREES C.
      USE PARM
      X2=MIN(DST0(ISA),STMP(LID(2,ISA),ISA))
      X1=SQRT(TMX(IRF(ISA))*SRAD(IRF(ISA)))
      SNPKT=.3333*(2.*X2+TX)
      F=TSNO(ISA)/(TSNO(ISA)+EXP(SCRP(16,1)-SCRP(16,2)*TSNO(ISA)))
      SML=MAX(0.,X1*(1.52+.54*F*SNPKT))
      SML=MIN(SML,SNO(ISA))
      SNO(ISA)=SNO(ISA)-SML
      REP=MAX(1.,.042*SML)
      PRFF=.042
      DUR=24.
      RETURN
      END