      SUBROUTINE HSWBLD(P,Q,ET,O,SSF,RG,SNO,ESW,BSW,QWT,SSFI,FPF,QDR,QRF&
     &,RBK,CPVH,KW,MSO)
!     APEX0806
!     THIS SUBPROGRAM CHECKS THE SOIL WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION KW(MSO)
      DF=BSW+P-Q-ET-O-ESW-SSF+RG-SNO+QWT+SSFI+FPF-QDR-QRF+RBK-CPVH
	  WRITE(KW(1),2)
      WRITE(KW(1),3)DF,BSW,P,Q,ET,O,SSF,RG,SNO,QWT,SSFI,FPF,QDR,QRF,&
      RBK,CPVH,ESW
      RETURN
    2 FORMAT(/T10,'SOIL WATER BALANCE')
    3 FORMAT(5X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,'PCP =',E13.6,2X,&
      'Q   =',E13.6,2X,'ET  =',E13.6,2X,'PRK =',E13.6/5X,'SSF =',E13.6,&
      2X,'IRG =',E13.6,2X,'SNO =',E13.6,2X,'QIN =',E13.6,2X,'SSFI=',&
      E13.6,2X,'FPF =',E13.6/5X,'QDR =',E13.6,2X,'QRF =',E13.6,2X,&
      'RBK =',E13.6,2X,'CPVH=',E13.6,2X,'FSW =',E13.6)
      END