      SUBROUTINE HSWBL(P,Q,ET,O,SSF,RG,SNO,SWE,SWB,QWT,SSFI,FPF,QDR,QRF,&
      RBK,CPVH,PSOQ,RGDL,ISA,KFL,KW,NBSA,MSO)
!     APEX0806
!     THIS SUBPROGRAM CHECKS THE SOIL WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION NBSA(ISA),KW(MSO),KFL(MSO+1)
      DF=SWB+P-Q-ET-O-SWE-SSF+RG-SNO+QWT+SSFI+FPF-QDR-QRF+RBK-CPVH+PSOQ-&
      RGDL 
      PER=100.*DF/SWE
	  IF(ABS(PER)>1..OR.KFL(1)>0)THEN
	      WRITE(KW(1),2)ISA,NBSA(ISA) 
	      WRITE(KW(1),3)PER,DF,SWB,P,Q,ET,O,SSF,RG,SNO,QWT,SSFI,FPF,QDR,&
	      QRF,RBK,CPVH,PSOQ,SWE
	  END IF
      RETURN
    2 FORMAT(/T10,'SOIL WATER BALANCE',2X,'SA#= ',I8,1X,'ID= ',I8)	 
    3 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,&
      'PCP =',E13.6,2X,'Q   =',E13.6,2X,'ET  =',E13.6/5X,'PRK =',E13.6,&
      2X,'SSF =',E13.6,2X,'IRG =',E13.6,2X,'SNO =',E13.6,2X,'QIN =',&
      E13.6,2X,'SSFI=',E13.6/5X,'FPF =',E13.6,2X,'QDR =',E13.6,2X,&
      'QRF =',E13.6,2X,'RBK =',E13.6,2X,'CPVH=',E13.6,2X,'PSOQ=',E13.6/&
      5X,'FSW =',E13.6)
      END