      SUBROUTINE NCBL(BC,YOC,YCWN,VBC,QBC,RSPC,TFOC,RSDC,BURN,SCOU,DEP,&
      FTC,ISA,KW,NBSA,MSO,JRT)
!     APEX0806
!     THIS SUBPROGRAM COMPUTES THE C BALANCE AT THE END OF THE
!     SIMULATION
      DIMENSION NBSA(ISA),KW(MSO)
	  JRT=0
      DF=BC-YOC-YCWN-VBC-QBC-RSPC+TFOC+RSDC-BURN-SCOU+DEP-FTC
      PER=100.*DF/FTC
!	  IF(ABS(PER)<1.)RETURN
      WRITE(KW(1),3)ISA,NBSA(ISA)
	  WRITE(KW(1),1)PER,DF,BC,YOC,YCWN,VBC,QBC,RSPC,RSDC,BURN,TFOC,SCOU,&
	  DEP,FTC
      BC=FTC
	  JRT=1
      RETURN
    1 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BTOT=',E13.6,2X,&
      'Y   =',E13.6,2X,'YWN =',E13.6,2X,'PRK =',E13.6/5X,'Q   =',E13.6,&
      2X,'RSPC=',E13.6,2X,'RSDC=',E13.6,2X,'BURN=',E13.6,2X,'TFOC=',&
      E13.6,2X,'SCOU=',E13.6/5X,'DEP =',E13.6,2X,'FTOT=',E13.6)
    3 FORMAT(/T10,'C BALANCE',2X,'SA#= ',I8,1X,'ID= ',I8)
      END