      SUBROUTINE NDNIT
!     APEX0806
!     THIS SUBPROGRAM ESTIMATES DAILY LOSS OF SOL N BY DENITRIFICATION.
      USE PARM
      RTO=100.*(ST(ISL,ISA)-FC(ISL,ISA))/(PO(ISL,ISA)-FC(ISL,ISA))
      F=RTO/(RTO+EXP(SCRP(27,1)-SCRP(27,2)*RTO))
	  X1=MIN(PRMT(36),1.-EXP(-CDG*WOC(ISL,ISA)/WT(ISL,ISA)))
      WDN=WNMN(ISL,ISA)*X1*F
	  IF(WDN>WNMN(ISL,ISA))WDN=WNMN(ISL,ISA)
      WNMN(ISL,ISA)=MAX(1.E-5,WNMN(ISL,ISA)-WDN)
      RETURN
      END