      SUBROUTINE NEVN
!     APEX0806
!     THIS SUBPROGRAM ESTIMATES UPWARD SOL N MOVEMENT CAUSED BY SOIL 
!     EVAPORATION.
      USE PARM
      IF(NEV==1)RETURN
      LD1=LID(1,ISA)
      TOT=0.
      DO KK=NEV,2,-1
          ISL=LID(KK,ISA)
          IF(WNMN(ISL,ISA)<.001)CYCLE
          XX=SEV(ISL,ISA)*PRMT(86)*WNMN(ISL,ISA)/(ST(ISL,ISA)+SEV(ISL,ISA))
          TOT=TOT+XX
          WNMN(ISL,ISA)=MAX(1.E-5,WNMN(ISL,ISA)-XX)
      END DO
      WNMN(LD1,ISA)=WNMN(LD1,ISA)+TOT
      RETURN
      END