      SUBROUTINE NEVP
!     APEX0806
!     THIS SUBPROGRAM ESTIMATES UPWARD SOLUBLE P MOVEMENT CAUSED BY SOIL
!     EVAPORATION.
      USE PARM
      IF(NEV==1)RETURN
      LD1=LID(1,ISA)
      TOT=0.
      DO KK=NEV,2,-1
          ISL=LID(KK,ISA)
          IF(WPML(ISL,ISA)<.001.OR.SEV(ISL,ISA)<.001)CYCLE
          X1=MIN(.75,PRMT(59)*SEV(ISL,ISA)/WT(ISL,ISA))
          XX=WPML(ISL,ISA)*X1
          TOT=TOT+XX
          WPML(ISL,ISA)=WPML(ISL,ISA)-XX
          TEV1=TEV1+SEV(ISL,ISA)
      END DO
      TEVP=TEVP+TOT
      TEV1=TEV1+SEV(LD1,ISA)
      WPML(LD1,ISA)=WPML(LD1,ISA)+TOT
      RETURN
      END