      SUBROUTINE NPMN(CS)
!     APEX0806
!     THIS SUBPROGRAM SIMULATES MINERALIZATION P USING PAPRAN EQS
      USE PARM
      TKG=RSD(ISL,ISA)*1000.
      !AD1=WPML(ISL,ISA)+WPO(ISL,ISA)+FOP(ISL,ISA)+WPOU(ISL,ISA)
      HMP=DHN(ISL,ISA)*WPO(ISL,ISA)/(WHSN(ISL,ISA)+WHPN(ISL,ISA))
      !HMP=.125*DHN(ISL,ISA)
      R4=.58*TKG
      X1=MAX(1.,FOP(ISL,ISA)+WPML(ISL,ISA))
      CPR=MIN(2000.,R4/X1)
      CPRF=EXP(-.693*(CPR-200.)/200.)
      DECR=MAX(.01,.05*CPRF*CS)
      RMP=DECR*FOP(ISL,ISA)
      RMPU=DECR*WPOU(ISL,ISA)
	  IF(WPOU(ISL,ISA)>1.E-5)THEN
		  WPOU(ISL,ISA)=WPOU(ISL,ISA)-RMPU
	  ELSE
		  RMPU=WPOU(ISL,ISA)
		  WPOU(ISL,ISA)=0.
	  END IF
	  IF(FOP(ISL,ISA)>1.E-5)THEN
		  FOP(ISL,ISA)=FOP(ISL,ISA)-RMP
	  ELSE
		  RMP=FOP(ISL,ISA)
		  FOP(ISL,ISA)=0.
	  END IF
	  X2=.8*(RMP+RMPU)
      WMP=X2+HMP
      X1=WPML(ISL,ISA)+WMP
	  IF(X1<0.)THEN
		  WMP=-WPML(ISL,ISA)
		  HMP=WMP-X2
		  WPML(ISL,ISA)=0.
      ELSE
		  WPML(ISL,ISA)=WPML(ISL,ISA)+WMP
	  END IF
      WPO(ISL,ISA)=WPO(ISL,ISA)-HMP+.2*(RMP+RMPU)
      !AD2=WPML(ISL,ISA)+WPO(ISL,ISA)+FOP(ISL,ISA)+WPOU(ISL,ISA)	
      !DF=AD1-AD2
      !IF(ABS(DF)>.0001)WRITE(KW(1),1)IY,MO,KDA,ISA,ISL,AD1,AD2,WPML(ISL,ISA),&
      !WPO(ISL,ISA),FOP(ISL,ISA),WPOU(ISL,ISA),HMP,RMP,RMPU,WMP,DF
    !1 FORMAT('!!!!!',5I4,20E13.5)  
      RETURN
      END