      SUBROUTINE NYON
!     APEX0806
!     THIS SUBPROGRAM PREDICTS DAILY ORGANIC N AND HUMUS LOSS, GIVEN
!     SOIL LOSS AND ENRICHMENT RATIO.
      USE PARM
      LD1=LID(1,ISA)
      TOT=WHPN(LD1,ISA)+WHSN(LD1,ISA)+WBMN(LD1,ISA)+WLMN(LD1,ISA)+WLSN&
      (LD1,ISA)
      YN(IDO)=YEW*TOT
      YNWN(IDO)=YEWN*TOT
      X1=MAX(1.E-5,1.-YEW-YEWN)
      WBMN(LD1,ISA)=WBMN(LD1,ISA)*X1
      WHSN(LD1,ISA)=WHSN(LD1,ISA)*X1
      WHPN(LD1,ISA)=WHPN(LD1,ISA)*X1
      WLSN(LD1,ISA)=WLSN(LD1,ISA)*X1
      WLMN(LD1,ISA)=MAX(.001,WLMN(LD1,ISA)*X1)
      X4=YMNU(IDO)*WNOU(LD1,ISA)/(RSDM(LD1,ISA)+1.E-10)
      YNOU(IDO)=MAX(0.,X4)
      WNOU(LD1,ISA)=MAX(1.E-5,WNOU(LD1,ISA)-X4)
      RETURN
      END