      SUBROUTINE NYPAV
!     APEX0806
!     THIS SUBPROGRAM PREDICTS DAILY P LOSS, GIVEN SOIL LOSS AND
!     ENRICHMENT RATIO.
      USE PARM
      LD1=LID(1,ISA)
      X2=WPML(LD1,ISA)
      YP(IDO)=MIN(YEW*WPO(LD1,ISA)**PRMT(32),.5*WPO(LD1,ISA))
      YPWN(IDO)=YEWN*WPO(LD1,ISA)
      WPO(LD1,ISA)=WPO(LD1,ISA)-YP(IDO)
      X4=MIN(WPOU(LD1,ISA),YMNU(IDO)*WPOU(LD1,ISA)/(RSDM(LD1,ISA)+1.E-10))
      YPOU(IDO)=X4
      WPOU(LD1,ISA)=WPOU(LD1,ISA)-X4
      W=10.*RFV(IRF(ISA))/(RSDM(LD1,ISA)+1.E-5)
      PRU=MIN(.5*WPMU(LD1,ISA),1.2*WPMU(LD1,ISA)*W/(W+73.1))
	  XX=QVOL(IDO)/RFV(IRF(ISA))
	  QPU(IDO)=PRU*XX*XX
	  WPMU(LD1,ISA)=WPMU(LD1,ISA)-PRU
	  VPU(ISA)=PRU-QPU(IDO)
      QAPY=YEW*X2
      X2=X2-QAPY+VPU(ISA)
      V=QVOL(IDO)+PKRZ(LD1)
      X1=MAX(5.*V,WT(LD1,ISA)*PRMT(8))
      IF(QVOL(IDO)>0.)THEN
          IF(LBP>2)THEN
              RTO=(10.*WPO(LD1,ISA)/WT(LD1,ISA))**PRMT(30)
              QP(IDO)=MIN(.5*X2,X2*QVOL(IDO)*RTO/X1)
          ELSE
              QP(IDO)=X2*QVOL(IDO)/X1
          END IF
          X2=X2-QP(IDO)
      END IF
      VAP(ISA)=MIN(.5*X2,X2*PKRZ(LD1)/X1)
      WPML(LD1,ISA)=X2-VAP(ISA)
	  QP(IDO)=QP(IDO)+QPU(IDO)
	  YMP=WPMA(LD1,ISA)*YEW
      WPMA(LD1,ISA)=WPMA(LD1,ISA)-YMP
      YP(IDO)=YP(IDO)+YMP+QAPY+X4
      TPRK=TPRK+PKRZ(LD1)
      TPSP=TPSP+VAP(ISA)
      RETURN
      END