      SUBROUTINE NYPA
!     APEX0806
!     THIS SUBPROGRAM PREDICTS DAILY P LOSS, GIVEN SOIL LOSS AND
!     ENRICHMENT RATIO.
      USE PARM
      LD1=LID(1,ISA)
      QPU(IDO)=0.
      X2=WPML(LD1,ISA)
      !AD1=X2+WPMA(LD1,ISA)+WPO(LD1,ISA)
      YP(IDO)=YEW*WPO(LD1,ISA)**PRMT(32)
      YPWN(IDO)=YEWN*WPO(LD1,ISA)
      X4=MIN(WPOU(LD1,ISA),YMNU(IDO)*WPOU(LD1,ISA)/(RSDM(LD1,ISA)+1.E-10))
      YPOU(IDO)=X4
      WPOU(LD1,ISA)=WPOU(LD1,ISA)-X4
      WPO(LD1,ISA)=WPO(LD1,ISA)-YP(IDO)-YPWN(IDO)
      QAPY=YEW*X2
      APWN=YEWN*X2
      X2=X2-QAPY-APWN
      V=QVOL(IDO)+PKRZ(LD1)
      V5=5.*V
      X1=MAX(V5,WT(LD1,ISA)*PRMT(8))
      XZ=MAX(V5,WT(LD1,ISA))
      VPU(ISA)=MIN(.5*WPMU(LD1,ISA),WPMU(LD1,ISA)*PKRZ(LD1)/XZ)
	  WPMU(LD1,ISA)=MAX(0.,WPMU(LD1,ISA)-VPU(ISA))
	  IF(QVOL(IDO)>0.)THEN
          IF(LBP>2)THEN
              RTO=(10.*WPO(LD1,ISA)/WT(LD1,ISA))**PRMT(30)
              QP(IDO)=MIN(.5*X2,X2*QVOL(IDO)*RTO/X1)
          ELSE
	          XX=QVOL(IDO)/X1
              QP(IDO)=X2*XX
              QPU(IDO)=WPMU(LD1,ISA)*XX*(1.-URBF(ISA))
          END IF
          QP(IDO)=QP(IDO)*(1.-URBF(ISA))+URBF(ISA)*QURB(IDO)*.0015
          X2=X2-QP(IDO)
      END IF
      VAP(ISA)=MIN(.5*X2,X2*PKRZ(LD1)/WT(LD1,ISA))
      WPML(LD1,ISA)=X2-VAP(ISA)
      WPMU(LD1,ISA)=MAX(0.,WPMU(LD1,ISA)-QPU(IDO))
      QP(IDO)=QP(IDO)+QPU(IDO)
	  YMP=WPMA(LD1,ISA)*YEW
	  PMWN=YEWN*WPMA(LD1,ISA)
      WPMA(LD1,ISA)=WPMA(LD1,ISA)-YMP-PMWN
      YP(IDO)=YP(IDO)+YMP+QAPY
      YPWN(IDO)=YPWN(IDO)+PMWN+APWN
	  TPRK=TPRK+PKRZ(LD1)
      TPSP=TPSP+VAP(ISA)
      !AD2=WPML(LD1,ISA)+WPMA(LD1,ISA)+WPO(LD1,ISA)
      !DF=AD1-QP(IDO)-VAP(ISA)-YP(IDO)-YPWN(IDO)-AD2
      !IF(ABS(DF)>1.E-5)WRITE(KW(1),1)IY,MO,KDA,AD1,QP(IDO),VAP(ISA),YP&
      !(IDO),YPWN(IDO),AD2,DF
    !1 FORMAT(1X,'!!!!!',3I4,10E13.5)  
      RETURN
      END