      SUBROUTINE PESTF
!     APEX0806
!     THIS SUBPROGRAM CALCULATES THE PEST FACTOR BASED ON THE MINIMUM
!     PEST FACTOR (PST(JJK)) FOR CROP JJK AND THE SUM OF DAILY PEST
!     DAMAGE (PSTS)
      USE PARM 
      IF(PSTF(ISA)<=0.)THEN
          PSTF(ISA)=1.
          IPST(ISA)=1
      ELSE
          Z1=PSTX*PSTF(ISA)/IPST(ISA)
          PSTF(ISA)=1.-(1.-PST(JJK))*Z1/(Z1+EXP(SCRP(9,1)-SCRP(9,2)*Z1))
      END IF   
      RETURN
      END 