      SUBROUTINE PSTAPP
!     APEX0806
!     THIS SUBPROGRAM APPLIES PESTICIDES TO CROP CANOPY & SOIL.
      USE PARM 
      KP=LPC(IRO(ISA),KP1(ISA),ISA)
      X2=PSTR(IRO(ISA),KP1(ISA),ISA)
      XX=X2*HE(JT1)*MASP
      SMMP(1,KP,MO,IDOA(ISA))=SMMP(1,KP,MO,IDOA(ISA))+XX
      SMMRP(5,KP,MO)=SMMRP(5,KP,MO)+XX*WSA(ISA)
      X3=PSTE(IRO(ISA),KP1(ISA),ISA)
      VARP(1,KP,IDO)=XX
	  X1=PCST(KP)*X2
      COST(ISA)=COST(ISA)+X1
      IF(KFL(31)>0)WRITE(KW(31),1)ISA,NBSA(ISA),IYR,MO,KDA,PSTN(KP),&
      KDC(JJK),KDP(KP),IHC(JT1),NBE(JT1),NBT(JT1),X1,X1,X2,FULU(JT1)
      PSTF(ISA)=PSTF(ISA)-X3*1000.
      IF(NOP>0.OR.NBSA(ISA)==ISAP)WRITE(KW(1),6)ISA,NBSA(ISA),IYR,&
      MO,KDA,PSTN(KP),X2,HE(JT1),X3
      IF(TLD(JT1)<1.E-10)THEN
          X1=SLAI(JJK,ISA)
          IF(X1<.06)FGC(ISA)=0.
          X1=XX*FGC(ISA)
          PFOL(KP,ISA)=PFOL(KP,ISA)+X1
          PSTZ(KP,LID(1,ISA),ISA)=PSTZ(KP,LID(1,ISA),ISA)+XX-X1
          GO TO 5
      END IF
      DO K=1,NBSL(ISA)
          ISL=LID(K,ISA)
          IF(TLD(JT1)<=Z(ISL,ISA))EXIT
      END DO
      PSTZ(KP,ISL,ISA)=PSTZ(KP,ISL,ISA)+XX
    5 IF(KP1(ISA)<NPST(IRO(ISA),ISA))KP1(ISA)=KP1(ISA)+1
      RETURN
    1 FORMAT(1X,2I8,1X,I4,2I2,2X,A16,I6,2X,4I4,F10.2,10X,3F10.2)
    6 FORMAT(1X,2I8,1X,I4,2I2,2X,A16,2X,'APPL RATE = ',F7.1,'g/ha',2X,&
      'APPL EFF =',F6.3,2X,'KILL EFF = ',F6.3)
      END