      SUBROUTINE PSTFRQ(QQ,YY,SSPX,ISX,IXP)
!     APEX0806
!     THIS SUBPROGRAM CALCULATES MAXIMUM ANNUAL PESTICIDE LOSSES FOR 1, 
!     4, 21, 60, AND 90 DAY INTERVALS.
      USE PARM
      DIMENSION NY(5)
      DIMENSION SSPX(MPS)
      DATA NY/1,4,21,60,90/
      SQB(1,ISX)=QQ
      SYB(1,ISX)=YY
      DO I=2,5
		  SQB(I,ISX)=SQB(I,ISX)+QQ-VQ(NXP(NY(I)),ISX)
	      SYB(I,ISX)=SYB(I,ISX)+YY-VY(NXP(NY(I)),ISX)
      END DO
      DO K=1,NDP
		  PQST=QPST(K,IDO)+SSPX(K) 
		  SPQ(1,K,ISX)=PQST
		  SPY(1,K,ISX)=YPST(K,IDO)
		  DO I=2,5
			  SPQ(I,K,ISX)=SPQ(I,K,ISX)+PQST-PVQ(K,NXP(NY(I)),ISX)
			  IF(SPQ(I,K,ISX)<1.E-3.OR.SQB(I,ISX)<1.E-3)THEN
	    		  SPQC(I,K,ISX)=0.
	          ELSE
				  SPQC(I,K,ISX)=100.*SPQ(I,K,ISX)/SQB(I,ISX)
			  END IF		   
		      SPY(I,K,ISX)=SPY(I,K,ISX)+YPST(K,IDO)-PVY(K,NXP(NY(I)),ISX)
          END DO	  
		  DO I=1,5
			  IF(APQ(I,K,IY,ISX)<SPQ(I,K,ISX))THEN
 			      APQ(I,K,IY,ISX)=SPQ(I,K,ISX)
				  AQB(I,K,IY,ISX)=SQB(I,ISX)
			  END IF
		      IF(APQC(I,K,IY,ISX)<SPQC(I,K,ISX))APQC(I,K,IY,ISX)=SPQC(I,K,ISX)
		      IF(APY(I,K,IY,ISX)>SPY(I,K,ISX))CYCLE
			  APY(I,K,IY,ISX)=SPY(I,K,ISX)
			  AYB(I,K,IY,ISX)=SYB(I,ISX)
		  END DO
	   	  PVQ(K,IXP,ISX)=PQST
		  PVY(K,IXP,ISX)=YPST(K,IDO)
		  VQ(IXP,ISX)=QQ
		  VY(IXP,ISX)=YY
	  END DO
      RETURN
      END