      SUBROUTINE PSTTBL
!     APEX0806
!     THIS SUBPROGRAM READS PESTICIDE TABLE TO DETERMINE PESTICIDE
!     PARAMETERS
      USE PARM 
      DIMENSION YTP(7)
      IF(NDP>0)THEN
          DO L=1,NDP
              IF(KDP(L)==JX(7))RETURN
          END DO
      END IF
      NDP=NDP+1
      KDP(NDP)=JX(7)
      KDP1(JX(7))=NDP
!     READ PESTICIDE TABLE
!  1  PSTN = PESTICIDE NAME
!  2  PSOL = PESTICIDE SOLUBILITY (ppm)
!  3  PHLS = PESTICIDE HALF LIFE IN SOIL (d)
!  4  PHLF = PESTICIDE HALF LIFE ON FOLIAGE (d)
!  5  PWOF = PESTICIDE WASH OFF FRACTION
!  6  PKOC = PESTICIDE ORGANIC C ADSORPTION COEF
!  7  PCST = PESTICIDE COST ($/KG)
      J1=-1
      DO WHILE(J1/=JX(7))
          READ(KR(8),1,IOSTAT=NFL)J1,PSTN(NDP),(YTP(L),L=2,7)
          IF(NFL/=0)THEN
              WRITE(*,*)'PEST NO = ',JX(7),' NOT IN PEST LIST FILE &
              SAID = ',NBSA(ISA)
              PAUSE
              STOP
          END IF
      END DO
      PSOL(NDP)=YTP(2)
      PHLS(NDP)=YTP(3)
      PHLF(NDP)=YTP(4)
      PWOF(NDP)=YTP(5)
      PKOC(NDP)=YTP(6)
      PCST(NDP)=YTP(7)
      REWIND KR(8)
      RETURN
      !1 FORMAT(I5,1X,A16,F12.0,3F8.0,F10.0,F8.0)    
    1 FORMAT(I5,1X,A16,6E16.6)
      END