      SUBROUTINE RESQB(QI,QO,P,EV,PRK,SSF,RGA,SNO,SWF,SWI,SSFI,QRF,RBK,&
      ISA,KW,NBSA,MSO)
!     APEX0806
!     THIS SUBPROGRAM CHECKS THE RESERVOIR WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION NBSA(ISA),KW(MSO)
      DF=SWI+QI+P-QO-EV-PRK-SSF-QRF+RGA+SSFI-RBK-SWF-SNO
	  PER=100.*DF/SWF
	  IF(ABS(PER)<1.)RETURN
	  WRITE(KW(1),2)
      WRITE(KW(1),3)PER,DF,SWI,P,QI,QO,EV,PRK,SSF,QRF,RGA,SSFI,RBK,SWF,SNO
	  WRITE(KW(1),4)ISA,NBSA(ISA) 
      RETURN
    2 FORMAT(/T10,'RESERVOIR WATER BALANCE')
    3 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,&
      'PRCP=',E13.6,2X,'QI  =',E13.6,2X,'QO  =',E13.6/5X,'EVP =',E13.6,&
      2X,'SEP =',E13.6,2X,'SSF =',E13.6,2X,'QRF =',E13.6,2X,'IRGA=',&
      E13.6,2X,'SSFI=',E13.6/5X,'RBK =',E13.6,2X,'FSW =',E13.6,2X,&
      'SNO =',E13.6)
    4 FORMAT(10X,'SA#= ',I8,1X,'ID= ',I8)
      END