      SUBROUTINE RTSED
!     APEX0806
!     THIS SUBPROGRAM ROUTES SEDIMENT THRU A REACH USING A DAILY TIME
!     STEP. POTENTIAL SEDIMENT CONC IS ESTIMATED AS A FUNCTION OF
!     VELOCITY. NET DEPOSITION OR DEGRADATION MAY RESULT DEPENDING ON
!     CONC OF REACH INFLOW, VEGETATIVE COVER, AND CHANNEL ERODIBILITY.
      USE PARM 
      LD1=LID(1,IDN2)
      Q1=WYLD(IDO)
      Q2=Q1
      DEPC(IDN2)=0.
      WSAX=RWSA(IDN1)
	  WSAX1=10.*WSAX
	  Y1=YSD(NDRV,IDN1)
	  VARH(33,IDO)=WSAX1*Q1/86400.
	  SMMH(33,MO,IDO)=SMMH(33,MO,IDO)+Q1
	  VARH(1,IDO)=WSAX1*QVOL(IDN1)/86400.
	  SMMH(1,MO,IDO)=SMMH(1,MO,IDO)+QVOL(IDN1)
	  VARH(5,IDO)=WSAX*Y1
	  SMMH(5,MO,IDO)=SMMH(5,MO,IDO)+VARH(5,IDO)
	  VARH(8,IDO)=WSAX*YN(IDN1)
	  SMMH(8,MO,IDO)=SMMH(8,MO,IDO)+VARH(8,IDO)
	  VARH(10,IDO)=WSAX*YP(IDN1)	
	  SMMH(10,MO,IDO)=SMMH(10,MO,IDO)+VARH(10,IDO)
      YU1=YMNU(IDN1)
      RSM1=RSDM(LD1,IDN2)
      RSMC=.1*RSM1*RCHL(IDN2)*RCTW(IDN2)/WSA(IDN2)
      RSMF=.1*RSM1*RFPL(IDN2)*RFPW(IDN2)/WSA(IDN2)
      !AD1=0.
      !DO I=1,NBSL(IDN2)
          !ISL=LID(I,IDN2)
          !AD1=AD1+PSTZ(1,ISL,IDN2)
      !END DO
      !TOT1=WNOU(LD1,IDN2)+WNMN(LD1,IDN2)+WBMN(LD1,IDN2)+WHSN(LD1,IDN2)+&
      !WHPN(LD1,IDN2)+WLSN(LD1,IDN2)+WLMN(LD1,IDN2)
      !ADI=WPOU(LD1,IDN2)+WPMU(LD1,IDN2)
	  YC(IDN1)=MAX(0.,YC(IDN1)-YCOU(IDN1))
      ZCH=RCHD(IDN2)
      CBW=RCBW(IDN2)
      CIN=.1*Y1/Q1+1.E-10
	  VARH(7,IDN2)=1.E6*CIN
	  CUN=.1*YU1/Q1
      IF(YU1<.01)THEN
          RTNU=0.
          RTCU=0.
          RTPU=0.
      ELSE
          RTCU=YCOU(IDN1)/YU1
          RTNU=YNOU(IDN1)/YU1
          RTPU=YPOU(IDN1)/YU1
      END IF
      X4=WSAX/(360.*(DUR+TC(IDN1)))
      QAV=Q1*X4
      XMNU=0.
      XNOU=0.
      XCOU=0.
      XPOU=0.
      DEP=0.
      DEG=0.
      WSW=0.
      CYFP=0.
      QFP=0.
      QO=0.
      Y2=0.
      CYCH=0.
      Q3=0.
      IF(FFPQ(IDN2)>0)THEN
          QFP=QAV*FFPQ(IDN2)
          QQ=QAV-QFP
      ELSE
          IF(QCAP(IDN2)>=QAV)GO TO 1
          QQ=QCAP(IDN2)
          QFP=QAV-QCAP(IDN2)
      END IF
      DFP=(QFP/RFPX(IDN2))**.6
      VFP=QFP/(DFP*RFPW(IDN2))
      X1=QFP*VFP
      CYFP=PRMT(19)*VFP**PRMT(18)
      Q3=QFP/X4
      SMM(79,MO,IDN2)=SMM(79,MO,IDN2)+Q3
      VAR(79,IDN2)=Q3
      VFPA(IDN2)=VFPA(IDN2)+VFP
      IF(VFP>VFPB(IDN2))VFPB(IDN2)=VFP
      NBFF(IDN2)=NBFF(IDN2)+1
      TRT=RFPL(IDN2)/(3.6*VFP)
      XX=MIN(SATC(LID(2,IDN2),IDN2),FPSC)
      IF(FFPQ(IDN2)>0)THEN
          CALL HFPF(Q1,TRT,XX,Q2)
          FPF(IDN2)=Q1-Q2
      ELSE
          FPF(IDN2)=MIN(Q3,XX*TRT)
      END IF
      Q2=MAX(0.,Q1-FPF(IDN2))
      SMM(98,MO,IDN2)=SMM(98,MO,IDN2)+FPF(IDN2)
	  VARH(4,IDO)=WSAX1*FPF(IDN2)/86400.
	  SMMH(4,MO,IDO)=SMMH(4,MO,IDO)+FPF(IDN2)
	  QO=MAX(0.,Q3-FPF(IDN2))
      IF(QO>0.)THEN
          X7=PRMT(45)*TRT*PSZM(IDN1)
          IF(X7<10.)THEN
              F=1.-EXP(-X7)
          ELSE
              F=1.
          END IF   
          X5=10.*(CYFP*QO-CIN*Q3)*F
          IF(X5>0.)THEN
              DEG=EK(IDN2)*CVF(IDN2)*X5
          ELSE
              DEP=-X5
          END IF
!         DEP=Y1*(1.-EXP(-PRMT(81)*TRT))
          GO TO 11
      END IF
      DEP=10.*CIN*Q3
      DPU=10.*WSAX*CUN*Q3
      XMNU=XMNU-DPU
      XNOU=XNOU-YNOU(IDN1)
      XCOU=XCOU-YCOU(IDN1)
      XPOU=XPOU-YPOU(IDN1)
      WSW=RFPW(IDN2)
!     IF(XNOU>0.)WRITE(KW(1),42)IDN2,NBSA(IDN2),IY,MO,KDA,YNOU(IDN1),
!    1XNOU
      GO TO 34
    1 X1=0.
      QQ=QAV
      GO TO 34
   11 X7=2.*PRMT(45)*TRT
      IF(X7<10.)THEN
          F=1.-EXP(-X7)
      ELSE
          F=1.
      END IF
      X5=10.*(CYFP*QO-CUN*Q3)*F
      IF(X5>0.)GO TO 32
      DGU=X5*WSAX
      RTOC=RTCU
      RTON=RTNU
      RTOP=RTPU
      GO TO 33
   32 IF(RSMF<.1)GO TO 34
      DGU=MIN(.9*RSMF,.5*CVF(IDN2)*X5)*WSA(IDN2)
      RTON=WNOU(LD1,IDN2)/RSM1
      RTOP=WPOU(LD1,IDN2)/RSM1
      RTOC=WCOU(LD1,IDN2)/RSM1
   33 XMNU=XMNU+DGU
      XNOU=XNOU+DGU*RTON/WSAX
      XCOU=XCOU+DGU*RTOC/WSAX
      XPOU=XPOU+DGU*RTOP/WSAX
   34 IF(QQ<1.E-5)THEN
          VCH=0.
          IF(DEP<=1.E-5)DEP=Y1
          GO TO 10
      END IF
      DCH=MAX(.1,ZCH*LOG10(QQ+1.)/LOG10(QCAP(IDN2)+1.))
      X3=SQRT(RCSS(IDN2)*RCSS(IDN2)+1.)
      DO IT=1,10
          A=DCH*(CBW+DCH*RCSS(IDN2))
          P=CBW+2.*X3*DCH
          Q=A**1.66667*RCHX(IDN2)/P**.66667
          FU=Q-QQ
          X6=MAX(1.,QQ)
          IF(ABS(FU/X6)<.01)GO TO 14
          R=A/P
          DFDD=RCHX(IDN2)*(1.6667*R**.6667*(CBW+2.*DCH*RCSS(IDN2))-1.333&
          *R**1.66667*X3)
          DCH=DCH-FU/DFDD
      END DO
      WRITE(KW(1),16)IDN2,NBSA(IDN2),IYR,MO,KDA,QQ,Q,DFDD,DCH,ZCH
   14 VCH=QQ/A
      TRT=RCHL(IDN2)/(3.6*VCH)
      CYCH=PRMT(19)*VCH**PRMT(18)
      VCHA(IDN2)=VCHA(IDN2)+VCH
      IF(VCH>VCHB(IDN2))VCHB(IDN2)=VCH
      NBCF(IDN2)=NBCF(IDN2)+1
      Q3=QQ/X4
      X7=PRMT(45)*TRT*PSZM(IDN1)
      IF(X7<10.)THEN
          F=1.-EXP(-X7)
      ELSE
          F=1.
      END IF   
      X5=10.*(CYCH-CIN)*Q3
      IF(X5>0.)THEN
          X5=RCHK(IDN2)*X5
          DEG=DEG+X5
      ELSE
          DEP=DEP-X5*F
          DPMT(IDN2)=DPMT(IDN2)-X5
          ZCH=ZCH+.1*X5/BD(LD1,IDN2)
      END IF
!     DEP=DEP+(Y1-DEP)*(1.-EXP(-PRMT(81)*TRT))
      X7=2.*PRMT(45)*TRT
      IF(X7<10.)THEN
          F=1.-EXP(-X7)
      ELSE
          F=1.
      END IF   
      X5=10.*(CYCH-CUN)*Q3
      IF(X5>0.)THEN
          IF(RSMC<.1)GO TO 41
          DGU=MIN(.9*RSMC,.5*RCHC(IDN2)*X5)*WSA(IDN2)
          RTON=WNOU(LD1,IDN2)/RSM1
          RTOP=WPOU(LD1,IDN2)/RSM1
          RTOC=WCOU(LD1,IDN2)/RSM1
      ELSE
          DGU=X5*F*WSAX
          RTOC=RTCU
          RTON=RTNU
          RTOP=RTPU
      END IF   
      XMNU=XMNU+DGU
      XNOU=XNOU+DGU*RTON/WSAX
      XCOU=XCOU+DGU*RTOC/WSAX
      XPOU=XPOU+DGU*RTOP/WSAX
   41 DO I=1,NBSL(IDN2)
          ISL=LID(I,IDN2)
          IF(ZCH<Z(ISL,IDN2))EXIT
	  END DO
      ZCH=ZCH+.1*X5/BD(ISL,IDN2)
   10 VAV=MAX(.1,(X1+VCH*QQ)/QAV)
      TRT=RCHL(IDN2)/(3.6*VAV)
      TC(IDO)=TC(IDN1)+TRT
      TCAV(IDO)=TCAV(IDO)+TC(IDO)
      ALTC=1.-EXP(-TC(IDO)*PRFF)
      RQRB(IDO)=ALTC*Q1/TC(IDO)
      PRAV(IDO)=PRAV(IDO)+RQRB(IDO)
      IF(RQRB(IDO)>PRB(IDO))PRB(IDO)=RQRB(IDO)
      NQRB(IDO)=NQRB(IDO)+1
      IF(TC(IDO)>TCMX(IDO))THEN
          TCMX(IDO)=TC(IDO)
      ELSE
          IF(TC(IDO)<TCMN(IDO))TCMN(IDO)=TC(IDO)
      END IF    
      Y2=MAX(0.,Y1-DEP)
      Y2=Y2+DEG
      XX=10.*(CYCH*Q3+CYFP*QO)
      IF(XX<Y1)Y2=(.5*Y1+XX)/1.5
      IF(Y1>Y2)THEN
          DEP=Y1-Y2
          DEG=0.
      ELSE
          DEP=0.
          DEG=Y2-Y1
      END IF      
      SRCH(14,IDO)=SRCH(14,IDO)+DEG
      SRCH(13,IDO)=SRCH(13,IDO)+DEP
	  SDEP=SDEP+DEP*WSAX
	  SDEG=SDEG+DEG*WSAX
	  IF(WSW<1.E-10)WSW=RCTW(IDN2)
	  WSU=.1*WSW*RFPL(IDN2)
	  EV=MIN(Q2,PRMT(91)*EO*WSU/WSA(IDN2))
	  VARH(3,IDO)=EV*WSAX1/86400.
	  SMMH(3,MO,IDO)=SMMH(3,MO,IDO)+VARH(3,IDO)
	  Q2=Q2-EV
      YU1=WSAX*YU1
      RSM1=WSA(IDN2)*RSM1
      IF(Q2<1.E-10)Y2=0.
	  IF(RSM1>YU1)THEN
          X2=YU1
	  ELSE
	      X2=RSM1
	  END IF 
      X1=X2-XMNU
	  IF(X1<0.)XMNU=-X2
      YU2=YU1+XMNU
	  RSDM(LD1,IDN2)=(RSM1+YU1-YU2)/WSA(IDN2)
	  ZZ=WLS(LD1,IDN2)+WLM(LD1,IDN2)
      RTO=WLS(LD1,IDN2)/ZZ
      WLS(LD1,IDN2)=MAX(1.E-10,WLS(LD1,IDN2)-RTO*XMNU)
      WLM(LD1,IDN2)=WLM(LD1,IDN2)-XMNU*(1.-RTO)
      WNOU(LD1,IDN2)=MAX(0.,WNOU(LD1,IDN2)-XNOU)
      WCOU(LD1,IDN2)=MAX(0.,WCOU(LD1,IDN2)-XCOU)
      WPOU(LD1,IDN2)=MAX(1.E-5,WPOU(LD1,IDN2)-XPOU)
      TOT=0.
      DRTO=MIN(1.,Y2/(Y1+1.E-10))
	  DRTO=MAX(1.E-5,DRTO)
      DRAV(IDO)=DRAV(IDO)+DRTO
      B1=LOG(DRTO)/4.47
      DO I=1,NSZ
	      PCTH(I,IDO)=PCT(I,IDN1)
          X1=MAX(-10.,B1*PSZY(I))
          PCT(I,IDO)=PCT(I,IDN1)*EXP(X1)
          TOT=TOT+PCT(I,IDO)
      END DO
      PSZM(IDO)=0.
      DO I=1,NSZ
          PCT(I,IDO)=PCT(I,IDO)/(TOT+1.E-10)
          PSZM(IDO)=PSZM(IDO)+PSZY(I)*PCT(I,IDO)
      END DO
      CY=.1*Y2/Q1
      IF(IERT==0)THEN
          B2=LOG10(DRTO)/2.699
          B1=1./.1**B2
          ERTO=MIN(3.5,B1*CIN**B2)
          IF(ERTO<1.)THEN
              ERTO=1.
              ERTP=1.
          END IF  
          ERTP=ERTO
      ELSE
          ERTO=MIN(3.5,PRMT(54)/CIN**PRMT(55))
          ERTP=MIN(3.5,PRMT(57)/CIN**PRMT(58))
      END IF
      ERAV(IDO)=ERAV(IDO)+ERTO
	  YNOU(IDO)=MAX(0.,YNOU(IDN1)+XNOU)
      YCOU(IDO)=MAX(0.,YCOU(IDN1)+XCOU)
	  RTO=MIN(ERTO*Y2/(Y1+1.E-10),1.)
      YN(IDO)=MAX(0.,YN(IDN1)*RTO)
      YC(IDO)=MAX(1.E-10,YC(IDN1)*RTO)
      X2=YN(IDN1)-YN(IDO)
      X1=1.+X2/WON(LD1,IDN2)
      WBMN(LD1,IDN2)=WBMN(LD1,IDN2)*X1
      WHSN(LD1,IDN2)=WHSN(LD1,IDN2)*X1
      WHPN(LD1,IDN2)=WHPN(LD1,IDN2)*X1
      WLSN(LD1,IDN2)=WLSN(LD1,IDN2)*X1
      WLMN(LD1,IDN2)=MAX(.001,WLMN(LD1,IDN2)*X1)
      X2=X2-XNOU
      SMM(91,MO,IDN2)=SMM(91,MO,IDN2)+X2
      VAR(91,IDN2)=X2
      X2=YC(IDN1)-YC(IDO)
      YC(IDO)=YC(IDO)+YCOU(IDO)
      X3=YC(IDN1)+YCOU(IDN1)-YC(IDO)
      SMM(102,MO,IDN2)=SMM(102,MO,IDN2)+X3
      VAR(102,IDN2)=X3
      DEPC(IDN2)=X3
      X1=1.+X2/WOC(LD1,IDN2)
	  IF(X1>.1)THEN
	      IF(X1>=1.2)THEN
              YC(IDO)=YC(IDN1)-.2*WOC(LD1,IDN2)
	          X1=1.2	 
	      END IF
	  ELSE
          YC(IDO)=YC(IDN1)+.9*WOC(LD1,IDN2)
	      X1=.1
	  END IF   
      WBMC(LD1,IDN2)=WBMC(LD1,IDN2)*X1
      WHSC(LD1,IDN2)=WHSC(LD1,IDN2)*X1
      WHPC(LD1,IDN2)=WHPC(LD1,IDN2)*X1
      WLSC(LD1,IDN2)=WLSC(LD1,IDN2)*X1
      WLMC(LD1,IDN2)=WLMC(LD1,IDN2)*X1
      X4=MIN(1.,WLMC(LD1,IDN2)/(WLMC(LD1,IDN2)+WLSC(LD1,IDN2)))
      WLMC(LD1,IDN2)=WLMC(LD1,IDN2)-X4*XCOU
      WLSC(LD1,IDN2)=MAX(.001,WLSC(LD1,IDN2)-XCOU*(1.-X4))
      YPOU(IDO)=MAX(0.,YPOU(IDN1)+XPOU)
      YP(IDO)=MAX(0.,YP(IDN1)*RTO)
      X2=YP(IDN1)-YP(IDO)
      WPO(LD1,IDN2)=WPO(LD1,IDN2)+X2
      X2=X2-XPOU
      SMM(92,MO,IDN2)=SMM(92,MO,IDN2)+X2
      VAR(92,IDN2)=X2
      YSD(NDRV,IDO)=Y2
      YMNU(IDO)=MAX(0.,YU2)/WSAX
	  QQ=Q2/Q1
	  QVOL(IDO)=QVOL(IDN1)*QQ
	  RSSF(IDO)=RSSF(IDN1)*QQ
	  SST(IDO)=SST(IDN1)*QQ
	  QDR(IDO)=QDR(IDN1)*QQ
	  QRF(IDO)=QRF(IDN1)*QQ
	  WYLD(IDO)=QVOL(IDO)+RSSF(IDO)+SST(IDO)+QDR(IDO)+QRF(IDO)
	  RSFN(IDO)=RSFN(IDN1)*QQ
	  QRFN(IDO)=QRFN(IDN1)*QQ
	  TSFN(IDO)=TSFN(IDN1)*QQ
	  QDRN(IDO)=QDRN(IDN1)*QQ
      XX=1.-QQ
      X2=QC(IDN1)*XX
      QC(IDO)=QC(IDN1)-X2
      WBMC(LD1,IDN2)=WBMC(LD1,IDN2)+X2
      WCMU(LD1,IDN2)=WCMU(LD1,IDN2)+X2
      SMM(102,MO,IDN2)=SMM(102,MO,IDN2)+X2
      VAR(102,IDN2)=VAR(102,IDN2)+X2
      DEPC(IDN2)=DEPC(IDN2)+X2
      X2=QN(IDN1)*XX
      QN(IDO)=QN(IDN1)-X2
      SMM(91,MO,IDN2)=SMM(91,MO,IDN2)+X2
      VAR(91,IDN2)=VAR(91,IDN2)+X2
      WNMN(LD1,IDN2)=WNMN(LD1,IDN2)+X2
      X2=QP(IDN1)*XX
      QP(IDO)=QP(IDN1)-X2
      WPML(LD1,IDN2)=WPML(LD1,IDN2)+X2
	  SMM(92,MO,IDN2)=SMM(92,MO,IDN2)+X2
      VAR(92,IDN2)=VAR(92,IDN2)+X2
      !ADF=WPOU(LD1,IDN2)+WPMU(LD1,IDN2)
      !DPPX=ADI-ADF
      !DF=DPPX+YPOU(IDN1)-YPOU(IDO)+QPU(IDN1)-QPU(IDO)
      !IF(ABS(DF)>.001.OR.ABS(DPPX-VAR(92,IDN2))>.001)WRITE(KW(1),'(A,5I4,10E13.5)')&
      !' ?????',IDN2,NBSA(IDN2),IY,MO,KDA,YPOU(IDN1),YPOU(IDO),QPU(IDN1),&
      !QPU(IDO),VAR(92,IDN2),DPPX,ADI,ADF,DF
      !TOT2=WNOU(LD1,IDN2)+WNMN(LD1,IDN2)+WBMN(LD1,IDN2)+WHSN(LD1,IDN2)+&
      !WHPN(LD1,IDN2)+WLSN(LD1,IDN2)+WLMN(LD1,IDN2)
      !DF=TOT1-TOT2+YN(IDN1)-YN(IDO)+QN(IDN1)-QN(IDO)+YNOU(IDN1)-YNOU(IDO)
      !IF(ABS(DF)>.01)WRITE(KW(1),'(A,5I4,20E13.5)')' !!!!!',IDN2,NBSA(IDN2),&
      !IY,MO,KDA,YN(IDN1),YN(IDO),YNOU(IDN1),YNOU(IDO),QN(IDN1),QN(IDO),&
      !TOT1,TOT2,DF
	  SP1=0.
	  SP2=0.
	  SP3=0.
	  SP4=0.
	  DO K=1,NDP
	      TOT=0.
	      AD3=0.
	      X1=RWSA(IDN1)*QPST(K,IDN1)
          AD3=AD3+X1
	      X2=QQ*X1
	      TOT=TOT+X1-X2
		  QPST(K,IDO)=X2/WSAX
		  X1=RWSA(IDN1)*TSPS(K,IDN1)
		  AD3=AD3+X1
	      X2=QQ*X1
	      TOT=TOT+X1-X2
		  TSPS(K,IDO)=X2/WSAX
		  X1=RWSA(IDN1)*RSPS(K,IDN1)
		  AD3=AD3+X1
	      X2=QQ*X1
	      TOT=TOT+X1-X2
		  RSPS(K,IDO)=X2/WSAX
	      X3=TOT/WSA(IDN2)
	      AD4=AD4+X3
		  PSTZ(K,LD1,IDN2)=PSTZ(K,LD1,IDN2)+X3
		  VARP(2,K,IDO)=QPST(K,IDO)
          SMMP(2,K,MO,IDO)=SMMP(2,K,MO,IDO)+QPST(K,IDO)
          VARP(4,K,IDO)=TSPS(K,IDO)
          SMMP(4,K,MO,IDO)=SMMP(4,K,MO,IDO)+TSPS(K,IDO)
          X1=WSAX*YPST(K,IDN1)
          AD3=AD3+X1
	      X2=X1*RTO
	      X3=(X1-X2)/WSA(IDN2)
	      PSTZ(K,LD1,IDN2)=PSTZ(K,LD1,IDN2)+X3
	      AD3=AD3/WSA(IDN2)
	      SMMP(13,K,MO,IDOA(IDN2))=SMMP(13,K,MO,IDOA(IDN2))+AD3
		  YPST(K,IDO)=X2/WSAX
          VARP(5,K,IDO)=YPST(K,IDO)
          SMMP(5,K,MO,IDO)=SMMP(5,K,MO,IDO)+YPST(K,IDO)
          VARP(11,K,IDO)=RSPS(K,IDO)
          SMMP(11,K,MO,IDO)=SMMP(11,K,MO,IDO)+RSPS(K,IDO)
          SP1=SP1+QPST(K,IDN1)
	      SP2=SP2+QPST(K,IDO)
	      SP3=SP3+YPST(K,IDN1)
          SP4=SP4+YPST(K,IDO)
      END DO
      AD2=0.
      DO I=1,NBSL(IDN2)
          ISL=LID(I,IDN2)
          AD2=AD2+PSTZ(1,ISL,IDN2)
      END DO
      !DF=AD1+(RWSA(IDN1)*(QPST(1,IDN1)+TSPS(1,IDN1)+RSPS(1,IDN1)+YPST(1,&
      !IDN1))-RWSA(IDN2)*(QPST(1,IDO)+TSPS(1,IDO)+RSPS(1,IDO)+YPST(1,&
      !IDO)))/WSA(IDN2)-AD2
      !IF(ABS(DF)>.001)WRITE(KW(1),20)IY,MO,KDA,AD1,QPST(1,IDN1),TSPS(1,&
      !IDN1),RSPS(1,IDN1),YPST(1,IDN1),QPST(1,IDO),TSPS(1,IDO),RSPS(1,&
      !IDO),YPST(1,IDO),AD2,DF
   	  VARH(34,IDO)=WSAX1*Q2/86400.
	  SMMH(34,MO,IDO)=SMMH(34,MO,IDO)+Q2
      VARH(2,IDO)=WSAX1*QVOL(IDO)/86400.
	  SMMH(2,MO,IDO)=SMMH(2,MO,IDO)+QVOL(IDO)
	  VARH(6,IDO)=WSAX*Y2
	  SMMH(6,MO,IDO)=SMMH(6,MO,IDO)+VARH(6,IDO)
	  VARH(9,IDO)=WSAX*YN(IDO)
	  SMMH(9,MO,IDO)=SMMH(9,MO,IDO)+VARH(9,IDO)
	  VARH(11,IDO)=WSAX*YP(IDO)
	  SMMH(11,MO,IDO)=SMMH(11,MO,IDO)+VARH(11,IDO)
	  VARH(12,IDO)=WSAX*(QN(IDN1)+RSFN(IDN1)+TSFN(IDN1)+QRFN(IDN1)+QDRN(IDN1))
	  SMMH(12,MO,IDO)=SMMH(12,MO,IDO)+VARH(12,IDO)
	  VARH(13,IDO)=WSAX*(QN(IDO)+RSFN(IDO)+TSFN(IDO)+QRFN(IDO)+QDRN(IDO))
	  SMMH(13,MO,IDO)=SMMH(13,MO,IDO)+VARH(13,IDO)
	  VARH(18,IDO)=WSAX*QP(IDN1)
	  SMMH(18,MO,IDO)=SMMH(18,MO,IDO)+VARH(18,IDO)
	  VARH(19,IDO)=WSAX*QP(IDO)
	  SMMH(19,MO,IDO)=SMMH(19,MO,IDO)+VARH(19,IDO)
	  VARH(26,IDO)=WSAX*SP1
	  SMMH(26,MO,IDO)=SMMH(26,MO,IDO)+VARH(26,IDO)
	  VARH(27,IDO)=WSAX*SP2
	  SMMH(27,MO,IDO)=SMMH(27,MO,IDO)+VARH(27,IDO)
	  VARH(28,IDO)=WSAX*SP3
	  SMMH(28,MO,IDO)=SMMH(28,MO,IDO)+VARH(28,IDO)
	  VARH(29,IDO)=WSAX*SP4
	  SMMH(29,MO,IDO)=SMMH(29,MO,IDO)+VARH(29,IDO)
	  VARH(32,IDO)=WSAX*(SP3-SP4)	
      SMMH(32,MO,IDO)=SMMH(32,MO,IDO)+VARH(32,IDO)
      RETURN
   16 FORMAT(1X,'***************PROBLEM DID NOT CONVERGE**************',&
      2I8,1X,I4,2I2,5E13.5)
   !20 FORMAT(1X,'!!!!!',3I4,20E13.5)     
      END