      SUBROUTINE TBURN
!     APEX0806
!     THIS SUBPROGRAM BURNS ALL STANDING AND FLAT CROP RESIDUE.
      USE PARM 
      LD1=LID(1,ISA)
      X2=1.-PRMT(56)
      ADD=0.
      SUM=0.
      DO J=1,LC
          IF(IDC(J)/=NDC(7).AND.IDC(J)/=NDC(8).AND.IDC(J)/=NDC(10))THEN
              RTO=MIN(.99,STL(J,ISA)/(DM(J,ISA)+1.E-10))
              X1=PRMT(56)*STL(J,ISA) 
              DM(J,ISA)=DM(J,ISA)-X1
              STL(J,ISA)=STL(J,ISA)-X1
              X3=PRMT(56)*UN1(J,ISA)*RTO
              UN1(J,ISA)=UN1(J,ISA)-X3
          END IF
          X5=STD(J,ISA)*PRMT(56)
          STD(J,ISA)=STD(J,ISA)-X5
          ADD=ADD+420.*X5
          STDL(J,ISA)=STDL(J,ISA)*X2
          X1=STDN(J,ISA)*PRMT(56)
          SMM(82,MO,ISA)=SMM(82,MO,ISA)+X1
          STDN(J,ISA)=MAX(1.E-5,STDN(J,ISA)-X1)
          SUM=SUM+X1+X3
          X1=STDP(J,ISA)*PRMT(56)
          FOP(LD1,ISA)=FOP(LD1,ISA)+X1
          STDP(J,ISA)=STDP(J,ISA)-X1
      END DO
      FOP(LD1,ISA)=FOP(LD1,ISA)+STDOP(ISA)
      RSDM(LD1,ISA)=RSDM(LD1,ISA)*X2
      SMM(11,MO,ISA)=SMM(11,MO,ISA)+SWLT(ISA)
      WLS(LD1,ISA)=WLS(LD1,ISA)*X2
      WLM(LD1,ISA)=WLM(LD1,ISA)*X2
      X1=PRMT(56)*WLSN(LD1,ISA)
      WLSN(LD1,ISA)=WLSN(LD1,ISA)-X1
      X3=PRMT(56)*WLMN(LD1,ISA)
      WLMN(LD1,ISA)=WLMN(LD1,ISA)-X3
      SUM=SUM+X1+X3+STDON(ISA)
      WLSL(LD1,ISA)=WLSL(LD1,ISA)*X2
      X1=PRMT(56)*WLSC(LD1,ISA)
      WLSC(LD1,ISA)=WLSC(LD1,ISA)-X1
      X3=PRMT(56)*WLMC(LD1,ISA)
      WLMC(LD1,ISA)=WLMC(LD1,ISA)-X3
      WLSLC(LD1,ISA)=WLSLC(LD1,ISA)*X2
      WLSLNC(LD1,ISA)=WLSC(LD1,ISA)-WLSLC(LD1,ISA)
      ADD=ADD+X1+X3
      SMM(140,MO,ISA)=SMM(140,MO,ISA)+ADD
      VAR(140,ISA)=ADD
      SMM(82,MO,ISA)=SMM(82,MO,ISA)+SUM
      VAR(82,ISA)=SUM
      RSD(LD1,ISA)=.001*(WLS(LD1,ISA)+WLM(LD1,ISA))
      SWLT(ISA)=0.
      STDO(ISA)=0.
      STDON(ISA)=0.
      STDOP(ISA)=0.
      RETURN
      END