      SUBROUTINE THVRT(YLSD,X6,X1,X3,JJ,LD1)
!     APEX0806
!     THIS SUBPROGRAM HARVESTS ROOT CROPS.
      USE PARM 
      JD=JJ
      LD1=LID(1,ISA)
      YLSD=0.
	  X1=ORHI(JT1)
	  XX=DM(JJ,ISA)
      XZ=X1*X3
      YY=XZ*HE(JT1)*X6
      X12=UN1(JJ,ISA)/XX
      X13=UP1(JJ,ISA)/XX
      X9=.9*STL(JJ,ISA)
	  X10=X12*X9
	  AD1=X10
	  JJK=JJ
	  CALL NCNSTD(.05,X9,X10,LD1)
      U2=X13*X9 
	  AD2=U2
	  FOP(LD1,ISA)=FOP(LD1,ISA)+U2
      YLN=YY*X12
      YLP=YY*X13
	  XX=X1*(1.-HE(JT1))
	  RW(JJ,ISA)=0.
	  DO J=1,LRD(ISA)
          ISL=LID(J,ISA)
          X11=RWT(ISL,JJ,ISA)*XX
	      RWT(ISL,JJ,ISA)=RWT(ISL,JJ,ISA)*(1.-X1)
	      X10=X11*X12
	      AD1=AD1+X10
	      JJK=JJ
	      CALL NCNSTD(.05,X11,X10,ISL)
          U2=X11*X13
	      AD2=AD2+U2 
          FOP(ISL,ISA)=FOP(ISL,ISA)+U2
          RW(JJ,ISA)=RW(JJ,ISA)+RWT(ISL,JJ,ISA)
      END DO
      YLD(JJ)=YY
      YLD1(JJ,ISA)=YY
      YLNF(JJ,ISA)=YLNF(JJ,ISA)+YLN
      YLPF(JJ,ISA)=YLPF(JJ,ISA)+YLP
	  STL(JJ,ISA)=STL(JJ,ISA)-X9
	  DM(JJ,ISA)=RW(JJ,ISA)+STL(JJ,ISA)
      UN1(JJ,ISA)=UN1(JJ,ISA)-YLN-AD1
!	TOT=TOT+UN1(JJK)
      UP1(JJ,ISA)=UP1(JJ,ISA)-YLP-AD2
	  HU(JJ,ISA)=HU(JJ,ISA)*.1
      SLAI(JJ,ISA)=.05
      RETURN
      END