      SUBROUTINE TRDST
!     APEX0806
!     THIS SUBPROGRAM PLACES 10% OF CROP RESIDUE AND ITS N AND P CONTENT
!     IN THE SURFACE LAYER STORAGE WHEN THE CROP IS HARVESTED, CONVERTS
!     ROOT WEIGHT TO RESIDUE, AND ZEROS CROP GROWTH ACCUMULATORS.
      USE PARM 
      STD(JJK,ISA)=STD(JJK,ISA)+STL(JJK,ISA)
      X1=STL(JJK,ISA)+RW(JJK,ISA)
      XX=UN1(JJK,ISA)/X1
      X3=UP1(JJK,ISA)/X1
      STDN(JJK,ISA)=STDN(JJK,ISA)+XX*STL(JJK,ISA)
      STDP(JJK,ISA)=STDP(JJK,ISA)+X3*STL(JJK,ISA)
      STDL(JJK,ISA)=STDL(JJK,ISA)+CLG(ISA)*STL(JJK,ISA)
      DO KK=1,LRD(ISA)
          K=LID(KK,ISA)
          X1=RWT(K,JJK,ISA)
          X2=X1*XX
          CALL NCNSTD(.1,X1,X2,K)
          FOP(K,ISA)=FOP(K,ISA)+X1*X3
          RWT(K,JJK,ISA)=0.
      END DO
      DM(JJK,ISA)=0.
      STL(JJK,ISA)=0.
      UN1(JJK,ISA)=0.
      UP1(JJK,ISA)=0.
      RW(JJK,ISA)=0.
      RD(JJK,ISA)=0.
      RETURN
      END