      FUNCTION WRAIN(R6,X,RST,IWI,MO)
!     APEX0806
!     THIS SUBPROGRAM COMPUTES DAILY PRECIPITATION AMOUNT FROM SKEWED
!     NORMAL DISTRIBUTION.
      DIMENSION RST(3,10,12)
      XLV=(X-R6)*R6+1.
      XLV=(XLV**3-1.)*2./RST(3,IWI,MO)
      WRAIN=XLV*RST(2,IWI,MO)+RST(1,IWI,MO)
      IF(WRAIN<.01)WRAIN=.01
      RETURN
      END